apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - prometheus/
  - grafana/
  - loki/
  - tempo/
  - alertmanager/
  - node-exporter/
  - kube-state-metrics/
  - promtail/

commonLabels:
  app.kubernetes.io/part-of: observability-stack

